services:
  supertonic-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supertonic-tts
    image: supertonic-tts:v101
    restart: unless-stopped
    ports:
      - "8020:8020"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"   # video
      - "109"  # render
    environment:
      - PYTHONUNBUFFERED=1
